# Generated by Django 4.1.5 on 2023-04-23 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0002_amazonuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.CharField(default='/static/img/sample.jpg', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazon.product')),
            ],
            options={
                'db_table': 'order_product',
            },
        ),
    ]
