# Generated by Django 4.1.5 on 2023-04-23 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0004_product_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time',
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='amazon.product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='world_id',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='order_product',
        ),
    ]
