# Generated by Django 4.1.5 on 2023-04-23 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0005_remove_order_time_order_count_order_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.TextField(default='Apple Watch'),
        ),
    ]
