# Generated by Django 4.1.5 on 2023-04-24 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0007_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='truck_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='amazon.warehouse'),
        ),
    ]
