# Generated by Django 4.1.5 on 2023-04-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0008_alter_order_truck_id_alter_order_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='package_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
