# Generated by Django 4.1.5 on 2023-04-25 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazon', '0013_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ups_account',
            field=models.TextField(blank=True, default='ups_huidan', null=True),
        ),
    ]
